version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Getting Started
  pre_build:
    commands:
      - echo Installing some packages and source NPM dependencies...
      - npm install -g json
      - chmod +x ./build_scripts/create_configuration.sh
      - sh ./build_scripts/create_configuration.sh
      - npm install
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Run all of your build related code if any
      - echo Build finished, now moving to S3
  post_build:
    commands:
      - echo Build completed on `date`
      #- aws deploy push --application-name codeDeployDemoSandip --s3-location s3://devops-with-aws-sandip-youtube/codedeploydemo/app.zip --ignore-hidden-files --region us-west-2
      # - aws deploy push --application-name "${CODE_DEPLOY_APPLICATION_NAME}" --s3-location "s3://${CODE_DEPLOY_S3_BUCKET}/codedeploydemo/app.zip" --ignore-hidden-files --region us-west-2
cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.npm/**/*'
    - 'node_modules/**/*'
